[package]
name = "zkml"
categories.workspace = true
edition.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
ark-std.workspace = true
ff.workspace = true
ff_ext = { version = "0.1.0", path = "../ff_ext" }
itertools.workspace = true
rayon.workspace = true
goldilocks.workspace = true
multilinear_extensions = { version = "0.1.0", path = "../multilinear_extensions" , features = ["parallel"]}
anyhow.workspace = true
sumcheck = { version = "0.1.0", path = "../sumcheck" }
derive_more = { version = "2.0.1", features = ["full"] }
transcript = { version = "0.1.0", path = "../transcript" }
tracing-subscriber.workspace = true
log = "0.4.25"
