name: "Test Suite"
permissions:
  contents: read

on:
  push:
    tags:
      - '**'
    branches:
      - main
  pull_request:

jobs:
  changes:
    name: Check for changes in zkML sources
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
      contents: read
    outputs:
      zkml_src: ${{ steps.filter.outputs.zkml_src }}
    steps:
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            zkml_src:
              - 'zkml/**'
              - '.github/workflows/tests.yml'

  test:
    name: Run zkML Rust tests
    needs: changes
    if: ${{ needs.changes.outputs.zkml_src != '[]' }}
    runs-on: ['hostname:hetzner-dedicated-6']
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10.13'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r zkml/assets/scripts/requirements.txt

      - name: Create directory for Python script assets
        run: mkdir -p ./ci_py_assets

      - name: Run Python script to generate assets
        run: python zkml/assets/scripts/llms/gpt2_internal.py --output-dir ./zkml/assets/scripts/llms/ --export-model

      - name: Set Environment Variables for Rust tests
        run: |
          echo "DEEPPROVE_CI=true" >> "$GITHUB_ENV"
          echo "DEEPPROVE_ASSET_DIR=${{ github.workspace }}/zkml/assets/scripts/llms/" >> "$GITHUB_ENV"

      - uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Run cargo test
        run: cargo test
        env:
          RUSTFLAGS: "-W warnings"

  formatting:
    name: Validate code formatting
    needs: changes
    runs-on: ubuntu-latest
    if: needs.changes.outputs.zkml_src == 'true'
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt
      - run: cargo fmt --all

  lint:
    name: Run Clippy
    needs: changes
    runs-on: ubuntu-latest
    if: ${{ needs.changes.outputs.zkml_src != '[]' }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Install protoc via apt
        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy

      - run: cargo clippy --all -- -D warnings
